### PR TITLE
Adds a pop up stage for find command

### PR DESCRIPTION
**Pull request by jinnieshin**
Added a pop up stage to show resulting details when a find command is executed.

Need to change the details shown to details of patients and staffs instead of the sample data given in AB3.

Need to design a UI for the pop up stage.

### CODE REVIEW

**Comment by jinnieshin** [comment]
I'll fix the stylecheck now

**Review by lukkesreysandeur — COMMENTED** [review]
Sorry but I think you might have misunderstood the issue. I believe you were supposed to add the ViewCommand class which could set the viewDetails flag to true, not immediately open a new window for the find command. Refer to the UG lines 99-105 to see the usage for view, and you can refer to your issue for more details.

**Comment by jinnieshin** [comment]
I've sticked to the original AB3's way of searching by name as at the time the patient and staff class was not there. I'll change it to ID later. Sorry that I misunderstood the function😂

**Comment by euph00** [comment]
Just curious, any updates on this end? List command for patients in a particular ward appears done (see #79) and will likely be merged soon. 1.2 can be closed after this PR closes.

We need to take screenshots of the product and upload it in the google document and then update Danny by tonight, so as and when you're done, do put in some dummy data as you're doing user testing and take the screenshots as you test functionalities. (Test new stuff such as listing patients, finding patient, listing staff, viewing specific patient)

Just paste those screenshots at the bottom of the google doc and ping Danny in the group 1 MS teams private channel, thanks!

**Pull request merged**
