### PR TITLE
Fixes (hopefully) issue where filteredpersonlist is not updating

### PR DESCRIPTION
**Pull request by euph00**

### CODE REVIEW

**Comment by pzhengze** [comment]
This doesn't work as FilteredList does not allow you to add or remove any object. It will throw a UnsupportedOperationException.

image
image

**Comment by pzhengze** [comment]
I think we should implement a private variable in Patientist for the PersonList and the getPersonList in Patientist to return this list as a unmodifiableObservableList so that we can make a make a FilterList with it. Then we add a new method to Patientist to clear and refresh this variable instead and consequently refreshing the FilterList as well.

**Comment by euph00** [comment]
> I think we should implement a private variable in Patientist for the PersonList and the getPersonList in Patientist to return this list as a unmodifiableObservableList so that we can make a make a FilterList with it. Then we add a new method to Patientist to clear and refresh this variable instead and consequently refreshing the FilterList as well.

Sounds reasonable, I’ll do that when I get home tonight or tomorrow morning if nobody is in a rush for this to be ready

If this is urgently needed today can go ahead and add it before I do

**Comment by pzhengze** [comment]
I think I'll test it out and implement this so that I can push my PR with the updates to storage so everyone can have a foundation to implement the new features needed.

**Comment by euph00** [comment]
> I think I'll test it out and implement this so that I can push my PR with the updates to storage so everyone can have a foundation to implement the new features needed.

Sounds good, thanks for the help

**Comment by pzhengze** [comment]
Alright the method above works. I'll close this PR and open a new one.

**Pull request closed without merging**
