### PR TITLE
Add lsward command

### LINKED ISSUE #32: As a user unfamiliar with the hospital, I want to list all ward names
So that I can have a high level view of the facility's wards

### PR DESCRIPTION
**Pull request by pzhengze**
This replaces the personslist column with a list of wards when lsward is used. Any other command replaces it with personlist. Still a little buggy. Patient count and Staff count does not update immediately.

This resolves #32

### CODE REVIEW

**Comment by euph00** [comment]
Just to check, what happens if index based command (eg delete 1) is called when displayed list is wards?

**Comment by euph00** [comment]
I see, good that behaviour is still defined. Brought it up because I thought it might be confusing/interpreted as a bug when index 1 on screen shows a ward but when you delete 1 it deletes a person silently. Might be good to mention this in UG

**Comment by pzhengze** [comment]
Maybe it might be better to make it as Jin suggested to always have 3 columns? Or maybe we make it such that when we lsward, we make the predicate of filteredpersonslist always false so that filteredpersonslist is empty and all index commands do not work until you list the persons again.

**Review by lukkesreysandeur — APPROVED** [review]
LGTM, but please change the spacing before merging. The latency issues we can try to fix in v1.4. The test cases I will try to add later.

**Pull request merged**
